jobs:
  include:
    - branch: master
      if: |
        NOT tag IS present
      services:
      - docker
      before_script:
      - docker version
      - sudo apt-get -y install jq wget
      env:
      - IMAGE="eisengrind/altv-server"
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - |
        for BRANCH in dev stable rc release
        do
           BUILD=$(wget --no-cache -qO- http://cdn.altv.mp/server/$BRANCH/x64_linux/update-info.json | jq '.latestBuildNumber')
           ./scripts/push.sh
        done
      - docker logout
    - branch: master
      if: |
        tag IS present &&
        tag =~ /^(stable|release|rc|dev)-[0-9]+$/
      services:
      - docker
      before_script:
      - docker version
      env:
      - IMAGE="eisengrind/altv-server"
      script:
      - travisTag=$TRAVIS_TAG
      - splitTag=(${travisTag//-/ })
      - echo ${splitTag[@]}
      - BRANCH=${splitTag[0]}
      - BUILD=${splitTag[1]}

      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - ./scripts/push.sh

      - docker logout
