jobs:
  include:
    - branch: master
      if: |
        tag IS present &&
        tag =~ /^(release|dev|rc)-[0-9]+$/
      services:
      - docker
      before_script:
      - docker version
      env:
      - IMAGE="eisengrind/altv-server"
      script:
      - travisTag=$TRAVIS_TAG
      - splitTag=(${travisTag//-/ })
      - echo ${splitTag[@]}
      - branch=${splitTag[0]}
      - build=${splitTag[1]}

      - docker build . --build-arg BRANCH=$branch -t $IMAGE:$build
      - docker tag $IMAGE:$build $IMAGE:$branch

      - docker build . -f ./dotnet.Dockerfile --build-arg BUILD=$build --build-arg BRANCH=$branch -t $IMAGE:$build-dotnet
      - docker tag $IMAGE:$build-dotnet $IMAGE:$branch-dotnet

      - docker build . -f ./nodejs.Dockerfile --build-arg BUILD=$build --build-arg BRANCH=$branch -t $IMAGE:$build-nodejs
      - docker tag $IMAGE:$build-nodejs $IMAGE:$branch-nodejs

      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - docker push $IMAGE:$build
      - docker push $IMAGE:$branch

      - docker push $IMAGE:$branch-dotnet
      - docker push $IMAGE:$build-dotnet

      - docker push $IMAGE:$build-nodejs
      - docker push $IMAGE:$branch-nodejs

      - docker logout
