name: ReleaseCI

on:
  push:
    tags:
      - "release-[0-9]+:js-[0-9]+:dotnet-[0-9]+"
      - "rc-[0-9]+:js-[0-9]+:dotnet-[0-9]+"
      - "dev-[0-9]+:js-[0-9]+:dotnet-[0-9]+"
      - "stable-[0-9]+:js-[0-9]+:dotnet-[0-9]+"

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      IMAGE: eisengrind/altv-voice-server
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y jq wget
      - name: modify push.sh
        run: chmod +x ./scripts/push.sh
      - name: build & push voice server images
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          tag=$TRAVIS_TAG
          parts=(${travisTag//:/ })
          gameServerTag=(${parts[0]})
          BRANCH=${gameServerTag[0]}
          BUILD=${gameServerTag[1]}
          jsModuleTag=(${parts[1]})
          jsModuleTagSplit=(${jsModuleTag//-/ })
          jsModuleBuild=${jsModuleTagSplit[1]}
          csharpModuleTag=(${parts[2]})
          csharpModuleTagSplit=(${csharpModuleTag//-/ })
          csharpModuleBuild=${csharpModuleSplit[1]}

          ./scripts/push.sh $IMAGE $BRANCH $BUILD $jsModuleBuild $csharpModuleBuild

          docker logout
