name: ReleaseCI

on:
  push:
    # "simple regex" for releases; source: https://github.com/semver/semver/issues/232
    tags:
      - '(release|rc|dev) \| ((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?|[a-zA-Z0-9]+)'

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      IMAGE: eisengrind/altv-server
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y jq wget
      - name: modify push.sh
        run: chmod +x ./scripts/push.sh
      - name: build & push altv server images
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          tag=${GITHUB_REF##*/}
          splitTag=(${tag// \| / })
          BRANCH=${splitTag[0]}
          BUILD=${splitTag[1]}

          ./scripts/push.sh $IMAGE $BRANCH $BUILD

          docker logout
