name: ReleaseCI

on:
  push:
    tags:
      - "release-[a-zA-Z0-9]+"
      - "rc-[a-zA-Z0-9]+"
      - "dev-[a-zA-Z0-9]+"

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      IMAGE: eisengrind/altv-voice-server
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y jq wget
      - name: modify push.sh
        run: chmod +x ./scripts/push.sh
      - name: build & push altv server images
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          tag=${GITHUB_REF##*/}
          splitTag=(${tag//-/ })
          BRANCH=${splitTag[0]}
          BUILD=${splitTag[1]}

          BRANCH=$(echo $TRAVIS_TAG | grep -o '[a-zA-z]*' | head -1)
          BUILD=$(echo $TRAVIS_TAG | sed -e 's/^[a-zA-Z]*-//g')

          ./scripts/push.sh $IMAGE $BRANCH $BUILD

          docker logout
